#!/usr/bin/env bash
# The Bash script iterates through numbers from 1 to 100. For each number, it checks if it's a multiple of both 
# 3 and 5 (FizzBuzz), 3 (Fizz),  5 (Buzz), or none of these. Based on the result, 
# it prints the corresponding output in a list format.

for i in $(seq 1 100); do
    if [ "$(( i % 5 ))" -eq 0 ] && [ "$(( i % 3))" -eq 0 ]; then
        echo "FizzBuzz"
    elif [ "$(( i % 3 ))" -eq 0 ]; then
        echo "Fizz"
    elif [ "$(( i % 5))" -eq 0 ]; then
        echo "Buzz"
    else
        echo "$i"
    fi

done