#!/usr/bin/env bash
# This script prints numbers from 0 to 12, and for each of them, prints numbers from 1 to 59
i=0
while ((i <= 12 )); do
    echo "Hour: $i"
    j=1
    while ((j <= 59)); do
        echo "$j"
        ((j++))
    done
    ((i++))
done
