#!/usr/bin/env bash
# This Bash script effectively checks for the existence, emptiness,
# and type of a file named "school". It uses conditional statements (if and else) to
# provide appropriate output based on the file's attributes.

if [ -e school ]; then
    echo "school file exists"
    if [ -s school ]; then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi
    if [ -f school ]; then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
